"use client";

import { useEffect, useRef } from "react";
import gsap from "gsap";
import SplitType from "split-type";

export default function Loader({ onComplete }: { onComplete: () => void }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const textRef = useRef<HTMLHeadingElement>(null);
  const maskRef = useRef<HTMLDivElement>(null);
  const topTextRefs = useRef<(HTMLDivElement | null)[]>([]);
  const bottomTextRefs = useRef<(HTMLDivElement | null)[]>([]);

  useEffect(() => {
    if (!containerRef.current || !textRef.current || !maskRef.current) return;

    const splitText = new SplitType(textRef.current, { types: "chars" });
    
    // Initial states for the main text: hidden via a clip-path like effect
    // We achieve this by moving chars down inside an overflow-hidden parent (which is .line generated by SplitType, or we just use y)
    gsap.set(splitText.chars, { 
      yPercent: 120,
      rotateX: -45,
      opacity: 0,
      color: "#333333",
      transformOrigin: "bottom center"
    });
    
    // Initial states for the small precision text
    gsap.set([...topTextRefs.current, ...bottomTextRefs.current], {
      opacity: 0,
      y: 10
    });

    const tl = gsap.timeline({
      onComplete: () => {
        onComplete();
      }
    });

    // 1. Fade in the small editorial details
    tl.to([...topTextRefs.current, ...bottomTextRefs.current], {
      opacity: 1,
      y: 0,
      duration: 1,
      stagger: 0.1,
      ease: "power2.out",
    }, 0.2)
    
    // 2. Main title reveals grandly, rotating up into place
    .to(splitText.chars, {
      yPercent: 0,
      rotateX: 0,
      opacity: 1,
      stagger: 0.04,
      duration: 1.5,
      ease: "expo.out",
    }, 0.5)

    // Efecto "pintado": letra por letra cambia a color claro
    .to(splitText.chars, {
      color: "#F5F5F5",
      stagger: 0.1,
      duration: 0.5,
      ease: "none"
    }, 0.8)

    // Slight tracking out for breathing room
    .to(textRef.current, {
      letterSpacing: "0.15em",
      duration: 2,
      ease: "power2.out",
    }, 0.5)

    // 3. The Exit Phase: Parallax upward
    // Small details fade out fast
    .to([...topTextRefs.current, ...bottomTextRefs.current], {
      opacity: 0,
      y: -10,
      duration: 0.5,
      ease: "power2.inOut"
    }, 2.5)

    // Main text slides up and out
    .to(splitText.chars, {
      yPercent: -120,
      opacity: 0,
      stagger: 0.02,
      duration: 1,
      ease: "expo.in"
    }, 2.6)
    
    // Background mask slides up, revealing the hero gracefully
    .to(maskRef.current, {
      yPercent: -100,
      duration: 1.5,
      ease: "expo.inOut",
    }, 2.8)
    
    // Kill the container
    .set(containerRef.current, {
      autoAlpha: 0,
    }, 4.3);

    return () => {
      tl.kill();
      splitText.revert();
    };
  }, [onComplete]);

  return (
    <div 
      ref={containerRef}
      className="fixed inset-0 z-[100] flex items-center justify-center pointer-events-none"
    >
      {/* Background Mask */}
      <div 
        ref={maskRef}
        className="absolute inset-0 bg-[#070707] w-full h-full will-change-transform"
      />

      {/* Editorial Corner Text (Top) */}
      <div className="absolute top-8 left-8 z-20 overflow-hidden">
        <div ref={el => { topTextRefs.current[0] = el; }} className="font-sans text-[10px] uppercase tracking-[0.2em] text-brand-light/40">
          Modonab
        </div>
      </div>
      <div className="absolute top-8 right-8 z-20 overflow-hidden">
        <div ref={el => { topTextRefs.current[1] = el; }} className="font-sans text-[10px] uppercase tracking-[0.2em] text-brand-light/40 text-right">
          Est. 2024
        </div>
      </div>

      {/* Editorial Corner Text (Bottom) */}
      <div className="absolute bottom-8 left-8 z-20 overflow-hidden">
        <div ref={el => { bottomTextRefs.current[0] = el; }} className="font-sans text-[10px] uppercase tracking-[0.2em] text-brand-light/40">
          Secuencia Digital
        </div>
      </div>
      <div className="absolute bottom-8 right-8 z-20 overflow-hidden">
        <div ref={el => { bottomTextRefs.current[1] = el; }} className="font-sans text-[10px] uppercase tracking-[0.2em] text-brand-light/40 text-right">
          Cargando
        </div>
      </div>

      {/* Main Typography */}
      <div className="overflow-hidden z-20 relative px-4">
        <h1 
          ref={textRef}
          style={{ perspective: "400px" }}
          className="font-[family-name:var(--font-instrument-serif)] text-7xl md:text-9xl text-brand-light uppercase tracking-tight leading-none"
        >
          Modonab
        </h1>
      </div>
    </div>
  );
}
